### ISSUE TITLE
How to install 

### ISSUE THREAD

**Issue by ydy1127** [genome/genome#1942] opened 2019-08-07 14:13 UTC
Hi, could you tell me how to install and use this software on Ubuntu?
I did not find the `README` file, so I tried to install genome but failed. The main installation steps are as follows:
1.run `git clone https://github.com/genome/genome.git`
2.go into the `bin` directory,run`./genome`,then an error message appears:
 `unable to locate spec: config at /usr/local/lib/x86_64-linux-gnu/perl/5.22.1/Genome/Site.pm line 19.
BEGIN failed--compilation aborted at /usr/local/lib/x86_64-linux-gnu/perl/5.22.1/Genome/Site.pm line 53.
Compilation failed in require at /usr/local/lib/x86_64-linux-gnu/perl/5.22.1/Genome.pm line 40.
Compilation failed in require at (eval 1) line 2.
BEGIN failed--compilation aborted at (eval 1) line 2.
BEGIN failed--compilation aborted at ./genome line 23.`
I really need your help. Looking forward to your reply!

**Comment by tmooney** [comment] 2019-08-07 14:19
This repository has a way of setting up a system to use the `Genome` modules: https://github.com/genome/gms

Our newer pipelines are all kept in https://github.com/genome/analysis-workflows and can be run with cwltool or Cromwell.  Depending on what you're trying to accomplish, that may be a better route to explore.

**Comment by tmooney** [comment] 2019-08-07 14:29
The newer version of MuSiC is maintained by the ding-lab in this repository: https://github.com/ding-lab/MuSiC2  Would that version work for you?

**Comment by ydy1127** [comment] 2019-08-07 14:39
Thank you very much for your prompt.
I have installed`  MuSiC2 `.
Now I need to study the `Genome MuSiC` version.Do you have any suggestions for MuSiC installation?

**Comment by tmooney** [comment] 2019-08-07 15:29
For the older version, the installation instructions were here: http://gmt.genome.wustl.edu/packages/genome-music/index.html  Unfortunately, the repository hosting those packages was taken offline last year.

I think at this point your best bet might be to try to follow the Standalone GMS instructions on the aforementioned https://github.com/genome/gms and run `gmt music` from there.

As to the specific error message you encountered, you might have better luck if you `cd` to `lib/perl` inside the git repository and then run `genome` (or `gmt`) from there.  (Alternatively, try setting the `XGENOME_CONFIG_SNAP` environment variable to point to the `etc` directory inside the repo.)  However, it'd be up to you to find and install any binary tools necessary to run the `gmt`s.  The standalone GMS route should help ensure those are available.

**Comment by ydy1127** [comment] 2019-08-08 01:06
Thank you very much for your answer, which is very useful to me. I will try your method very hard！

**Comment by ydy1127** [comment] 2019-08-09 02:56
Hello, I tried to install GMS according to your suggestion.

However, when I go into the `gms` directory to `make`, I got the following error:
```
Processing triggers for initramfs-tools ...
update-initramfs: Generating /boot/initrd.img-3.13.0-32-generic
wget https://s3fs.googlecode.com/files/s3fs-1.73.tar.gz
--2019-08-08 19:31:48--  https://s3fs.googlecode.com/files/s3fs-1.73.tar.gz
Resolving s3fs.googlecode.com (s3fs.googlecode.com)... 74.125.204.82, 2404:6800:4008:c07::52
Connecting to s3fs.googlecode.com (s3fs.googlecode.com)|74.125.204.82|:443... failed: Connection refused.
Connecting to s3fs.googlecode.com (s3fs.googlecode.com)|2404:6800:4008:c07::52|:443... failed: Network is unreachable.
make[2]: *** [done-host/s3fs-install] Error 4
make[2]: Leaving directory `/home/ydy/software/gms'
make[1]: *** [s3fs] Error 2
make[1]: Leaving directory `/home/ydy/software/gms'
make: *** [all] Error 2
```
When I visited the [s3fs.googlecode.com](url) in my browser, I got a 404 error.

In addition,I `cd` to `lib/perl` inside the git repository and then run `genome` (or `gmt`) from there, and try setting the `XGENOME_CONFIG_SNAP `environment variable to point to the` etc `directory inside the repo. But the initial problems remain unresolved.

Looking forward to your reply. Thank you very much for your help!

**Comment by ydy1127** [comment] 2019-08-12 02:51
Dear Authors,




    Follow the advice, I cd to lib/perl inside the git repository and then run genome (or gmt) from there, and try setting the XGENOME_CONFIG_SNAP​ environment variable to point to the etc directory inside the repo. But the initial problems remain unresolved.

 

     In addition, I tried to install GMS. However, when I go into the gms directory to make, I got the following error: 

 wget https://s3fs.googlecode.com/files/s3fs-1.73.tar.gz --2019-08-08 19:31:48--  https://s3fs.googlecode.com/files/s3fs-1.73.tar.gz
Resolving s3fs.g​ooglecode.com (s3fs.googlecode.com)... 74.125.204.82, 2404:6800:4008:c07::52
Connecting to s3fs.googlecode.com (s3fs.googlecode.com)|74.125.204.82|:443... failed: Connection refused.
Connecting to s3fs.googlecode.com (s3fs.googlecode.com)|2404:6800:4008:c07::52|:443... failed: Network is unreachable.
make[2]: *** [done-host/s3fs-install] Error 4
make[2]: Leaving directory `/home/ydy/software/gms'
make[1]: *** [s3fs] Error 2
make[1]: Leaving directory `/home/ydy/software/gms'
make: *** [all] Error 2
 

    When I visited the s3fs.googlecode.com in my browser, I got a 404 error.

    Looking forward to your reply. Thank you very much for your help!


------------------ 原始邮件 ------------------
发件人: "Thomas B. Mooney"<notifications@github.com>;
发送时间: 2019年8月7日(星期三) 晚上11:29
收件人: "genome/genome"<genome@noreply.github.com>;
抄送: "fairy^暖阳♀"<1614999088@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [genome/genome] How to install  (#1942)




For the older version, the installation instructions were here: http://gmt.genome.wustl.edu/packages/genome-music/index.html  Unfortunately, the repository hosting those packages was taken offline last year.
 
I think at this point your best bet might be to try to follow the Standalone GMS instructions on the aforementioned https://github.com/genome/gms and run gmt music from there.
 
As to the specific error message you encountered, you might have better luck if you cd to lib/perl inside the git repository and then run genome (or gmt) from there.  (Alternatively, try setting the XGENOME_CONFIG_SNAP environment variable to point to the etc directory inside the repo.)  However, it'd be up to you to find and install any binary tools necessary to run the gmts.  The standalone GMS route should help ensure those are available.

**Comment by tmooney** [comment] 2019-08-12 15:30
Unfortunately, it looks like the standalone GMS installation also relies on repositories that are no longer available.  (I think it is safe to say that nobody has tried to perform that installation in a while.)

I can reproduce your error when that environment variable is set to a bad value:
```
$ XGENOME_CONFIG_SNAP=/home/tmooney/git/genome/x genome config get config
Using libraries at /home/tmooney/git/genome/lib/perl
unable to locate spec: config at /home/tmooney/git/genome/lib/perl/Genome/Site.pm line 19.
BEGIN failed--compilation aborted at /home/tmooney/git/genome/lib/perl/Genome/Site.pm line 53.
Compilation failed in require at /home/tmooney/git/genome/lib/perl/Genome.pm line 40.
Compilation failed in require at (eval 2) line 2.
BEGIN failed--compilation aborted at (eval 2) line 2.
BEGIN failed--compilation aborted at /home/tmooney/git/genome/bin/genome line 23.
```

Setting the variable to point to the `etc` dir seems to work for me to get past that error, though:
```
$ XGENOME_CONFIG_SNAP=/home/tmooney/git/genome/etc genome config get config
Using libraries at /home/tmooney/git/genome/lib/perl

```
(The value of the `config` config is empty by default, so the output is blank.)  Are you seeing the exact same error when setting this variable?

**Comment by ydy1127** [comment] 2019-08-13 01:12
Thank you very much for your answer.
The environment variable I set in the `.bashrc` file before is:

`export XGENOME_CONFIG_SNAP=/home/yuandy/ydy/software/genome/etc:$XGENOME_CONFIG_SNAP`

Follow your code,I execute the following code in the` lib/perl` directory and still get an error prompt:

```
yuandy@bioubuntu ~/ydy/software/genome/lib/perl (master)>  XGENOME_CONFIG_SNAP=/home/yuandy/ydy/software/genome/etc genome config get config
Using libraries at /home/yuandy/ydy/software/genome/lib/perl
`/home/yuandy/ydy/software/genome/etc/:' is not a module name
BEGIN failed--compilation aborted at /home/yuandy/ydy/software/genome/lib/perl/Genome/Site.pm line 53.
Compilation failed in require at /home/yuandy/ydy/software/genome/lib/perl/Genome.pm line 40.
Compilation failed in require at (eval 2) line 1.
BEGIN failed--compilation aborted at (eval 2) line 1.
BEGIN failed--compilation aborted at /usr/local/bin/genome line 18.
```
It seems that the last problem has been solved, but a new one has emerged.

Is there something wrong with the setting of my environment variable?

Looking forward to your reply.

**Comment by ydy1127** [comment] 2019-08-13 08:21
Hi!Today I continue to try to install GMS.

I found that based on `https://github.com/genome/gms/wiki/Quick-VM-Tour`,  I could quickly use the integrated GMS in a virtual machine.

I copied the s3fs-1.73.tar.gz file from the` gms` folder in the virtual machine to my own `gms` directory and ran `make`, which fixed the above error, but prompted a new one:
```
[ -e genome-institute.asc ] || wget http://apt.genome.wustl.edu/ubuntu/files/genome-institute.asc
--2019-08-13 00:31:40--  http://apt.genome.wustl.edu/ubuntu/files/genome-institute.asc
Resolving apt.genome.wustl.edu (apt.genome.wustl.edu)... 128.252.233.45
Connecting to apt.genome.wustl.edu (apt.genome.wustl.edu)|128.252.233.45|:80... failed: Connection refused.
make[1]: *** [done-host/etc] Error 4
rm done-repo/download-apt-mirror-min-ubuntu-12.04-2015.04.09.tgz
make[1]: Leaving directory `/home/ydy/software/gms'
make: *** [all] Error 2
```
Still the issue of` http://apt.genome.wustl.edu/ubuntu/files/genome-institute.asc` have failed before.

Do you have a separate `genome-institute. asc` file that you can provide to me?

Looking forward to your reply. Thank you very much for your help!

**Comment by tmooney** [comment] 2019-08-13 14:21
The issue you're seeing with the `XGENOME_CONFIG_SNAP` variable is probably because of the trailing `:`.  There was no previous value of that variable, so there's nothing to join to.  It should be safe to overwrite it with simply the path to `etc` without the `:`.

That apt server is no longer available--it's the same one that hosted the old MuSiC packages.  Getting the `.asc` file isn't likely to be too useful on its own, since its purpose is to help with downloading packages from that server.  You might be able to pull the packages you need out of the VM, too and install them from local `.deb`s instead of from that apt server?

Out of curiosity, if you got the VM up and running, did the music command work from there just as a test?

**Comment by ydy1127** [comment] 2019-08-13 15:00
Thank you very much for your answer. I will try the method you provided tomorrow.

As you said,  the music command work from the VM just as a test. Besides, I can only use music using `genome tools music`.

The environment variable is set with an extra `:`, is it wrong to run
`XGENOME_CONFIG_SNAP=/home/yuandy/ydy/software/genome/etc genome config get config`from the command line？

Thank you very much for your help!

**Comment by ydy1127** [comment] 2019-08-14 07:03
Hello! Today I will continue installing `genome` as you suggested.

Firstly, I removed the redundant `:` from the environment variable. My environment variables are set as follows: `export XGENOME_CONFIG_SNAP=/home/yuandy/ydy/software/genome/etc`. And I solved the previous problem.

Then, Then the following error occurs:
```
yuandy@bioubuntu ~/ydy/software/genome/lib/perl (master)> genome config
Using libraries at /home/yuandy/ydy/software/genome/lib/perl
ERROR: Error while autoloading with 'use Genome::Model': Can't resolve data source from value 'Genome::DataSource::GMSchema' in class definition for Genome::Model
Error while autoloading with 'use Genome::DataSource::GMSchema': ds_gmschema_type must be defined at /home/yuandy/ydy/software/genome/lib/perl/Genome/DataSource/GMSchema.pm line 11.
Compilation failed in require at (eval 271) line 1.
```
I tried to add some new environment variables, as follows:
```
export XGENOME_DS_GMSCHEMA_TYPE=/home/yuandy/ydy/software/genome/etc 
export XGENOME_DS_GMSCHEMA_AUTH=/home/yuandy/ydy/software/genome/etc 
export XGENOME_DS_GMSCHEMA_LOGIN=/home/yuandy/ydy/software/genome/etc 
export XGENOME_DS_GMSCHEMA_SERVER=/home/yuandy/ydy/software/genome/etc 
```
It looks like the problem is solved, but run `genome` prompt: 
```
yuandy@bioubuntu ~/ydy/software/genome/lib/perl (master)> genome
Using libraries at /home/yuandy/ydy/software/genome/lib/perl
Sub-commands for genome:
ERROR: *** no genome modeling tools installed yet! ***
ERROR: Please specify valid params for 'genome'.
```
and run `genome config` prompt: 
```
yuandy@bioubuntu ~/ydy/software/genome/lib/perl (master)> genome config
Using libraries at /home/yuandy/ydy/software/genome/lib/perl
ERROR: Error while autoloading with 'use Genome::Model': Can't resolve data source from value 'Genome::DataSource::GMSchema' in class definition for Genome::Model
Error while autoloading with 'use Genome::DataSource::GMSchema': Class Genome::DataSource::GMSchema cannot initialize because of errors using parent class /home/yuandy/ydy/software/genome/etc.  Failed to find static method '__meta__' on /home/yuandy/ydy/software/genome/etc.  Does class /home/yuandy/ydy/software/genome/etc exist, and is it loaded? at /home/yuandy/ydy/software/genome/lib/perl/Genome/DataSource/GMSchema.pm line 11.
```
Is there any problem with the way I tried to set the environment variable?

**Comment by ydy1127** [comment] 2019-08-15 06:42
Hi,  I commented out the instructions related to `genome-institute.asc` in ` Makefile`according to your last answer.

Then I continue to run `make`,  prompt the url in `git clone http://github.com/openlava/openlava.git` does not exist. So I comment out the related instructions in the` Makefile` file.

I continue to run `make`, indicating that the ruby version is too low. I update the ruby version, but the error still exists.

However, a new terminal opens and the following interface appears:
```
setting GENOME_* variables...
updating PATH, PERL5LIB, and CLASSPATH for the GMS
configuring tab-completion...
ydy@ubuntu ~> gmt music
Sub-commands for gmt music:
 bmr                    ...  Calculate gene coverages and background mutation rates.     
 clinical-correlation        Correlate phenotypic traits against mutated genes, or       
                              against individual variants                                
 cosmic                      Match a list of variants to those in COSMIC, and highlight  
                              druggable targets     
```                              
Can I think I can use `genome`?
In addition, may I ask if `MuSiC` can not be used alone like `MuSiC2`, and can only rely on `genome` for use?

**Comment by tmooney** [comment] 2019-08-15 14:13
These variables:
```
export XGENOME_DS_GMSCHEMA_TYPE=
export XGENOME_DS_GMSCHEMA_AUTH= 
export XGENOME_DS_GMSCHEMA_LOGIN=
export XGENOME_DS_GMSCHEMA_SERVER=
```
are meant to point to a database server.  A database isn't required to run most `gmt`s though, so you can probably avoid dealing with that.

The old version of `MuSiC` does depend on some small parts of `genome`, but not most of it.  (The packages that used to exist would install the minimal parts of `genome` without all the extra complications you've been running into for other parts of it.)

It does look like you've got it mostly working, though!  There will be some executables that `MuSiC` relies on (like `joinx1.7`) so ensuring those are properly set up is the biggest issue you might yet run into.

**Comment by ydy1127** [comment] 2019-08-15 14:49
Thank you very much for your answer. 

As you said if I don't need to fix the database server, what command should I use to run `music` in `lib/perl`?

 I found the `Genome` directory in the `perl` directory contains the `music` module, but the folder is full of` .pm` files, no executable files. 

Some of the MuSiC dependent executables you mentioned, such joinx , were installed and configured when I installed MuSiC2.

**Comment by tmooney** [comment] 2019-08-15 14:55
Yes, `MuSiC` commands are implemented as a set of perl modules.  I would use `gmt music` to run the various music tools.  `gmt music play` is the main command that runs everything for some data.

(The `gmt` command is a perl script that calls the modules; you could possibly copy it and make a custom version that calls into the music tree directly if that seems useful.)

**Comment by ydy1127** [comment] 2019-08-15 15:06
Thank you very much for your reply!
I will try my best to execute the command you provided tomorrow.

**Comment by ydy1127** [comment] 2019-08-16 01:26
Hi!

I feel very sorry that errors occurred when I ran `gmt`, `gmt music` and` gmt music play` in the `lib/perl` directory.
```
yuandy@bioubuntu ~/ydy/software/genome/lib/perl (master)> gmt
Using libraries at /home/yuandy/ydy/software/genome/lib/perl
Sub-commands for gmt:
ERROR: *** no genome modeling tools installed yet! ***
ERROR: Please specify valid params for 'gmt'.
yuandy@bioubuntu ~/ydy/software/genome/lib/perl (master)> gmt music
Using libraries at /home/yuandy/ydy/software/genome/lib/perl
Sub-commands for gmt music:
ERROR: Please specify valid params for 'gmt music'.
yuandy@bioubuntu ~/ydy/software/genome/lib/perl (master)> gmt music play
Using libraries at /home/yuandy/ydy/software/genome/lib/perl
ERROR: pathway_file: Missing required parameter: --pathway-file.
ERROR: roi_file: Missing required parameter: --roi-file.
ERROR: maf_file: Missing required parameter: --maf-file.
ERROR: bam_list: Missing required parameter: --bam-list.
ERROR: output_dir: Missing required parameter: --output-dir.
ERROR: reference_sequence: Missing required parameter: --reference-sequence.
No backends registered for scope 'host' at /home/yuandy/ydy/software/genome/lib/perl/Genome/Sys/Lock.pm line 203.
        Genome::Sys::Lock::backends("host") called at /home/yuandy/ydy/software/genome/lib/perl/Genome/Sys/Lock.pm line 183
        Genome::Sys::Lock::release_all() called at /home/yuandy/ydy/software/genome/lib/perl/Genome/Sys/Lock.pm line 268
        Genome::Sys::Lock::END() called at /usr/local/bin/gmt line 0
        eval {...} called at /usr/local/bin/gmt line 0
END failed--call queue aborted.
```
The error appears to be caused by the fact that no genome modeling tools have been installed.

Do I need to execute any other instructions to install the genome modeling tools?

**Comment by tmooney** [comment] 2019-08-16 01:32
The `gmt music play` command looks like it mostly worked--except it is complaining that the required parameters to run MuSiC were not supplied.  Try `gmt music play --help` for more info on what parameters to pass.

(That lock error message is a little worrying, but since it happened in the `END` block it shouldn't have prevented the main program from executing.)

**Comment by ydy1127** [comment] 2019-08-16 01:44
As you suggested, I run `gmt music play --help` and prompt the following information:

```
yuandy@bioubuntu ~/ydy/software/genome/lib/perl (master)> gmt music play --help
Using libraries at /home/yuandy/ydy/software/genome/lib/perl

USAGE
 gmt music play --bam-list=? --roi-file=? --reference-sequence=? --output-dir=?
    --maf-file=? --pathway-file=? [--numeric-clinical-data-file=?]
    [--categorical-clinical-data-file=?] [--mutation-matrix-file=?] [--permutations=?]
    [--normal-min-depth=?] [--tumor-min-depth=?] [--min-mapq=?] [--show-skipped]
    [--genes-to-ignore=?] [--bmr=?] [--max-proximity=?] [--bmr-modifier-file=?]
    [--numerical-data-test-method=?] [--downsample-large-genes] [--skip-low-mr-genes] [--max-fdr=?]
    [--genetic-data-type=?] [--wu-annotation-headers] [--bmr-groups=?] [--separate-truncations]
    [--merge-concurrent-muts] [--skip-non-coding] [--skip-silent] [--glm-model-file=?]
    [--min-mut-genes-per-path=?] [--processors=?] [--aa-range=?] [--nuc-range=?]
    [--reference-build=?] [--show-known-hits] [--glm-clinical-data-file=?] [--use-maf-in-glm]
    [--omimaa-dir=?] [--cosmic-dir=?] [--verbose] [--clinical-correlation-matrix-file=?]
```
It looks like it will work, and I'm going to test it with a data set.

May I ask why running` gmt` does not prompt some subcommands as in GMS.

**Comment by ydy1127** [comment] 2019-08-16 02:25
I carefully read the description information in `gmt music play --help`, as follows:

`This command can be used to run all of the MuSiC analysis tools on a set of data. Please see The individual tools for further description of the parameters.`

How would I use an individual tool, for example I want to use subcommand `bmr` to calculate gene coverages and background mutation rates.

Thank you very much for your help!

**Comment by ydy1127** [comment] 2019-08-16 08:15
Hello!

I have added some necessary parameters according to your suggestion to test the `gmt music play ` command. Here are the results of the run.
```
yuandy@bioubuntu ~/ydy/software/genome/test_music (master)> gmt music play --roi-file example.roi_file --reference-sequence  fetch_chr_ucsc.hg19.fasta --bam-list example.bam_list1_test --output-dir ./  --maf-file CNIC-00-21-0001.merged4.filterpass.vep.maf --pathway-file hsa00001.keg --genetic-data-type gene
Could not find required additional columns in CNIC-00-21-0001.merged4.filterpass.vep.maf
ERROR: Command gmt music proximity did not return a true value.
No backends registered for scope 'host' at /home/yuandy/localperl/lib/5.30.0/x86_64-linux/Genome/Sys/Lock.pm line 203.
        Genome::Sys::Lock::backends("host") called at /home/yuandy/localperl/lib/5.30.0/x86_64-linux/Genome/Sys/Lock.pm line 183
        Genome::Sys::Lock::release_all() called at /home/yuandy/localperl/lib/5.30.0/x86_64-linux/Genome/Sys/Lock.pm line 268
        Genome::Sys::Lock::END() called at /usr/local/bin/gmt line 0
        eval {...} called at /usr/local/bin/gmt line 0
END failed--call queue aborted.
```
I found some requirements for the format of the input file in the instructions, such as:
```
 maf-file
    List of mutations using TCGA MAF specifications v2.3
```
However, the TCGA MAF specifications v2.3 version is no longer available.

So, I create a `MuSiC` compatible `MAF` file using `vcf2maf`. But the above error message still appears.

According to the error message prompted, may I ask whether some important columns are missing from my `MAF` file? Can I send my `maf_header` to you if possible?

Looking forward to your reply!

**Comment by tmooney** [comment] 2019-08-16 14:26
The various commands that you can run correspond to the modules named in the `lib/perl/Genome/Model/Tools/Music/` directory inside the repo: <https://github.com/genome/genome/tree/master/lib/perl/Genome/Model/Tools/Music>.  You should be able to run `gmt music bmr --help` to find out more about running `bmr` directly.

The error message says it is from the Proximity tool (`gmt music proximity`).  Running `gmt music proximity --help` will provide more information about the additional columns it requires:
https://github.com/genome/genome/blob/6abac49d0581024c2648aee6a8b8822e3c8fba3f/lib/perl/Genome/Model/Tools/Music/Proximity.pm#L32-L36

**Comment by ydy1127** [comment] 2019-08-19 02:45
Thank you very much for your answer.

As you say, I've tried to run the various commands that you can run correspond to the modules named in the `lib/perl/Genome/Model/Tools/Music/` directory before. As a result, some commands can be executed and some cannot. The details are as follows:

```
yuandy@bioubuntu ~/ydy/software/genome/lib/perl (master)> gmt music bmr --help
Using libraries at /home/yuandy/ydy/software/genome/lib/perl
Sub-commands for gmt music bmr:
```
I don't know if this is a subcommand not shown or not available. So, following the MuSiC2 test case, I executed the following command:
```
yuandy@bioubuntu ~/ydy/software/genome/lib/perl (master)> gmt music bmr calc-covg --help
Using libraries at /home/yuandy/ydy/software/genome/lib/perl

USAGE
 gmt music bmr calc-covg --roi-file=? --reference-sequence=? --bam-list=? --output-dir=?
    [--gene-covg-dir=?] [--cmd-list-file=?] [--cmd-prefix=?] [--normal-min-depth=?]
    [--tumor-min-depth=?] [--min-mapq=?]

SYNOPSIS
General usage:
```
It looks like it's working, so I tested it with MuSiC2 test data. But there was an error:
```
yuandy@bioubuntu ~/ydy/software/genome/test_music (master)> gmt music bmr calc-covg --roi-file example.roi_file --reference-sequence  fetch_chr_ucsc.hg19.fasta --bam-list  example.bam_list1_test --output-dir ./
[bam_header_read] EOF marker is absent. The input is probably truncated.
```
May I ask if I need to change my `bam-list` file?Can you provide me with the test case of` MuSiC`?

**Comment by tmooney** [comment] 2019-08-19 14:32
That looks like an error from `samtools` (or the underlying library) when a BAM is truncated.  The test data for the original MuSiC was in the same package repository as the software itself, so unfortunately it was also deleted last year.

If the BAMs are not truncated in the middle of a record, you might try converting the test BAMs you have to SAM and back to BAM so that the EOF marker is added appropriately.

Otherwise it may come down to finding other data to test with.  I don't know how appropriate it is for this specific tool, but I often test things using files in this archive: <https://github.com/genome/analysis-workflows/blob/a23f42ef49c10a588fd35a3afaad5de03e253533/example_data/exome_workflow.tgz>  Those BAMs I believe are from the HCC1395 dataset as described here: <https://github.com/genome/gms/wiki/HCC1395-WGS-Exome-RNA-Seq-Data>.

**Comment by ydy1127** [comment] 2019-08-20 01:21
Thank you very much for your answer.

Amazingly, the above error occurred during the run, but the command successfully ran and generated two folders `gene_covgs `and `roi_covgs`. The gene_covgs folder contains the `CNIC-00-21-0001.covg` file. The specific contents are as follows:
```
yuandy@bioubuntu ~/ydy/software/genome/test_music/gene_covgs (master)> vi CNIC-00-21-0001.covg
       1 #Gene Length  Covered AT_covd CG_covd CpG_covd
       2 A1BG  1754  0 0 0 0
       3 A1CF  2263  0 0 0 0
       4 A2M 4988  0 0 0 0
       5 A2ML1 5418  0 0 0 0
```
Can I consider MuSiC to be working properly?

As I mentioned in my last question, may I ask why the `gmt music bmr --help` does not show the subcommand of` bmr`, while the` gmt music bmr calc-covg --help` can show the subcommand of `calc-covg`?

Also,  can you provide the `MAF` test file needed to run the `music play` command?

**Comment by tmooney** [comment] 2019-08-20 14:54
It generally looks like it's working!  I would make sure that the results make sense; I'm not as familiar with interpreting the output of these files.

This is what I see for `gmt music bmr --help`:
```
[tmooney@blade18-1-16:~]$ gmt music bmr --help
Sub-commands for gmt music bmr:
 calc-bmr             Calculates mutation rates given per-gene coverage (from     
                       "music bmr calc-covg"), and a mutation list                
 calc-covg            Uses calcRoiCovg.c to count covered bases per-gene for each 
                       given tumor-normal pair of BAMs.                           
 calc-covg-helper     Uses calcRoiCovg.c to count covered bases per-gene for a    
                       tumor-normal pair of BAMs.                                 
 calc-wig-covg        Count covered bases per-gene for each given wiggle track    
                       format file. 
```
If that's not showing up, something must not be configured correctly in the resolution of sub-commands.  (That'd also explain why `gmt` by itself was giving that ```ERROR: *** no genome modeling tools installed yet! ***``` message.)  I'm not sure offhand what would cause that to not work properly... that subcommand resolution is part of `UR`, the ORM that the GMS uses.

I'm afraid I don't have a test MAF file.  I believe that you could get the three additional needed columns by running an annotator on the variants in the MAF file you're currently using.  (It should be safe to have extra additional columns in the file as well if desired, as long as the three listed in the help message are included.)

**Comment by ydy1127** [comment] 2019-08-21 10:34
Thank you very much for your answer!

As you suggested, I added the required three columns to the `MAF` file. And then continues to run the command  `gmt music play` with the following error:

`ERROR: Error running gmt music pfam: Cannot find the pfam db path. at /home/yuandy/localperl/lib/5.30.0/x86_64-linux/Genome/Model/Tools/Music/Pfam.pm line 90.`

Following the error, I think I need to download the `Pfam` database. Then I found the official download site [ftp://ftp.ebi.ac.uk/pub/databases/Pfam/releases/](url). 

But I don't know which version of `Pfam` file to download.

Also, because` Pfam` is the database file on which the command `gmt music play `depends,  I'm not sure exactly where to put it in order to use it properly.

Looking foward to your reply.

**Comment by ydy1127** [comment] 2019-08-26 11:16
Dear Authors,

  Hello!

  As for the problems I raised before, I have not found a reasonable solution, so that my research cannot be carried out normally .I really hope you can give me some suggestions.

  Looking forward to your reply!

**Comment by ydy1127** [comment] 2019-08-28 01:17
Thank you very much for your answer. I'll try as hard as you suggest.

**Comment by jasonwalker80** [comment] 2020-03-05 16:35
Closing. Please open a new Issue if additional assistance is needed.

**Closed by jasonwalker80** 2020-03-05 16:35 UTC
